// Archivo generado por scripts/build.mjs. No editar a mano.
const ___Account_js = require('./Account.js')
exports.Account = ___Account_js.Account
const ___Add_js = require('./Add.js')
exports.Add = ___Add_js.Add
const ___AlertCircle_js = require('./AlertCircle.js')
exports.AlertCircle = ___AlertCircle_js.AlertCircle
const ___ArrowLeft_js = require('./ArrowLeft.js')
exports.ArrowLeft = ___ArrowLeft_js.ArrowLeft
exports.ArrowLeftLong = ___ArrowLeft_js.ArrowLeftLong
const ___ArrowRight_js = require('./ArrowRight.js')
exports.ArrowRight = ___ArrowRight_js.ArrowRight
exports.ArrowRightLong = ___ArrowRight_js.ArrowRightLong
const ___Bag_js = require('./Bag.js')
exports.Bag = ___Bag_js.Bag
exports.ShoppingBag = ___Bag_js.ShoppingBag
const ___BagTimer_js = require('./BagTimer.js')
exports.BagTimer = ___BagTimer_js.BagTimer
exports.OrderPending = ___BagTimer_js.OrderPending
const ___Call_js = require('./Call.js')
exports.Call = ___Call_js.Call
exports.Phone = ___Call_js.Phone
const ___Car_js = require('./Car.js')
exports.Car = ___Car_js.Car
exports.Delivery = ___Car_js.Delivery
const ___Card_js = require('./Card.js')
exports.Card = ___Card_js.Card
exports.CreditCard = ___Card_js.CreditCard
const ___ChevronDown_js = require('./ChevronDown.js')
exports.ChevronDown = ___ChevronDown_js.ChevronDown
const ___ChevronLeft_js = require('./ChevronLeft.js')
exports.ChevronLeft = ___ChevronLeft_js.ChevronLeft
const ___ChevronRight_js = require('./ChevronRight.js')
exports.ChevronRight = ___ChevronRight_js.ChevronRight
const ___Clock_js = require('./Clock.js')
exports.Clock = ___Clock_js.Clock
const ___CloseCircle_js = require('./CloseCircle.js')
exports.CloseCircle = ___CloseCircle_js.CloseCircle
exports.XCircle = ___CloseCircle_js.XCircle
const ___Copy_js = require('./Copy.js')
exports.Copy = ___Copy_js.Copy
const ___Danger_js = require('./Danger.js')
exports.Danger = ___Danger_js.Danger
exports.AlertTriangle = ___Danger_js.AlertTriangle
const ___DocumentLike_js = require('./DocumentLike.js')
exports.DocumentLike = ___DocumentLike_js.DocumentLike
exports.Terms = ___DocumentLike_js.Terms
const ___Error_js = require('./Error.js')
exports.Error = ___Error_js.Error
const ___Eye_js = require('./Eye.js')
exports.Eye = ___Eye_js.Eye
const ___EyeLine_js = require('./EyeLine.js')
exports.EyeLine = ___EyeLine_js.EyeLine
const ___EyeSlash_js = require('./EyeSlash.js')
exports.EyeSlash = ___EyeSlash_js.EyeSlash
exports.EyeOff = ___EyeSlash_js.EyeOff
const ___GalleryAdd_js = require('./GalleryAdd.js')
exports.GalleryAdd = ___GalleryAdd_js.GalleryAdd
const ___Helmet_js = require('./Helmet.js')
exports.Helmet = ___Helmet_js.Helmet
const ___Home_js = require('./Home.js')
exports.Home = ___Home_js.Home
const ___InfoCircle_js = require('./InfoCircle.js')
exports.InfoCircle = ___InfoCircle_js.InfoCircle
exports.Info = ___InfoCircle_js.Info
const ___Location_js = require('./Location.js')
exports.Location = ___Location_js.Location
const ___Messages_js = require('./Messages.js')
exports.Messages = ___Messages_js.Messages
const ___Mobile_js = require('./Mobile.js')
exports.Mobile = ___Mobile_js.Mobile
const ___Moneys_js = require('./Moneys.js')
exports.Moneys = ___Moneys_js.Moneys
const ___Motorbiker_js = require('./Motorbiker.js')
exports.Motorbiker = ___Motorbiker_js.Motorbiker
const ___Paperclip_js = require('./Paperclip.js')
exports.Paperclip = ___Paperclip_js.Paperclip
exports.Attachment = ___Paperclip_js.Attachment
const ___PersonalCard_js = require('./PersonalCard.js')
exports.PersonalCard = ___PersonalCard_js.PersonalCard
exports.IdCard = ___PersonalCard_js.IdCard
const ___Receipt_js = require('./Receipt.js')
exports.Receipt = ___Receipt_js.Receipt
exports.Order = ___Receipt_js.Order
const ___ScanBarcode_js = require('./ScanBarcode.js')
exports.ScanBarcode = ___ScanBarcode_js.ScanBarcode
const ___Search_js = require('./Search.js')
exports.Search = ___Search_js.Search
const ___ShielVerified_js = require('./ShielVerified.js')
exports.ShielVerified = ___ShielVerified_js.ShielVerified
exports.ShieldCheck = ___ShielVerified_js.ShieldCheck
const ___Shop_js = require('./Shop.js')
exports.Shop = ___Shop_js.Shop
const ___ShoppingBagPlain_js = require('./ShoppingBagPlain.js')
exports.ShoppingBagPlain = ___ShoppingBagPlain_js.ShoppingBagPlain
const ___Star_js = require('./Star.js')
exports.Star = ___Star_js.Star
const ___Store_js = require('./Store.js')
exports.Store = ___Store_js.Store
const ___Succes_js = require('./Succes.js')
exports.Succes = ___Succes_js.Succes
const ___TickCircle_js = require('./TickCircle.js')
exports.TickCircle = ___TickCircle_js.TickCircle
exports.CheckCircle = ___TickCircle_js.CheckCircle
const ___Ticket_js = require('./Ticket.js')
exports.Ticket = ___Ticket_js.Ticket
const ___Trash_js = require('./Trash.js')
exports.Trash = ___Trash_js.Trash
const ___User_js = require('./User.js')
exports.User = ___User_js.User
const ___UserCard_js = require('./UserCard.js')
exports.UserCard = ___UserCard_js.UserCard
const ___UserSquare_js = require('./UserSquare.js')
exports.UserSquare = ___UserSquare_js.UserSquare
exports.Profile = ___UserSquare_js.Profile
const ___Warning_js = require('./Warning.js')
exports.Warning = ___Warning_js.Warning
const ____core_createIcon_native_js = require('../core/createIcon.native.js')
exports.createIcon = ____core_createIcon_native_js.createIcon
const ____core_defaults_js = require('../core/defaults.js')
exports.DEFAULTS = ____core_defaults_js.DEFAULTS