// Archivo generado por scripts/build.mjs. No editar a mano.
import { createElement } from 'react'
import {
  Account,
  Add,
  AlertCircle,
  ArrowLeft,
  ArrowRight,
  Bag,
  BagTimer,
  Call,
  Car,
  Card,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Clock,
  CloseCircle,
  Copy,
  Danger,
  DocumentLike,
  Error,
  Eye,
  EyeLine,
  EyeSlash,
  GalleryAdd,
  Helmet,
  Home,
  InfoCircle,
  Location,
  Messages,
  Mobile,
  Moneys,
  Motorbiker,
  Paperclip,
  PersonalCard,
  Receipt,
  ScanBarcode,
  Search,
  ShielVerified,
  Shop,
  ShoppingBagPlain,
  Star,
  Store,
  Succes,
  TickCircle,
  Ticket,
  Trash,
  User,
  UserCard,
  UserSquare,
  Warning,
} from './index.js'

export const iconRegistry = {
  "account": Account,
  "add": Add,
  "alert-circle": AlertCircle,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "bag": Bag,
  "bag-timer": BagTimer,
  "call": Call,
  "car": Car,
  "card": Card,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "clock": Clock,
  "close-circle": CloseCircle,
  "copy": Copy,
  "danger": Danger,
  "document-like": DocumentLike,
  "error": Error,
  "eye": Eye,
  "eye-line": EyeLine,
  "eye-slash": EyeSlash,
  "gallery-add": GalleryAdd,
  "helmet": Helmet,
  "home": Home,
  "info-circle": InfoCircle,
  "location": Location,
  "messages": Messages,
  "mobile": Mobile,
  "moneys": Moneys,
  "motorbiker": Motorbiker,
  "paperclip": Paperclip,
  "personal-card": PersonalCard,
  "receipt": Receipt,
  "scan-barcode": ScanBarcode,
  "search": Search,
  "shiel-verified": ShielVerified,
  "shop": Shop,
  "shopping-bag-plain": ShoppingBagPlain,
  "star": Star,
  "store": Store,
  "succes": Succes,
  "tick-circle": TickCircle,
  "ticket": Ticket,
  "trash": Trash,
  "user": User,
  "user-card": UserCard,
  "user-square": UserSquare,
  "warning": Warning,
}

export const iconNames = [
  "account",
  "add",
  "alert-circle",
  "arrow-left",
  "arrow-right",
  "bag",
  "bag-timer",
  "call",
  "car",
  "card",
  "chevron-down",
  "chevron-left",
  "chevron-right",
  "clock",
  "close-circle",
  "copy",
  "danger",
  "document-like",
  "error",
  "eye",
  "eye-line",
  "eye-slash",
  "gallery-add",
  "helmet",
  "home",
  "info-circle",
  "location",
  "messages",
  "mobile",
  "moneys",
  "motorbiker",
  "paperclip",
  "personal-card",
  "receipt",
  "scan-barcode",
  "search",
  "shiel-verified",
  "shop",
  "shopping-bag-plain",
  "star",
  "store",
  "succes",
  "tick-circle",
  "ticket",
  "trash",
  "user",
  "user-card",
  "user-square",
  "warning",
]

/** Renderiza un icono por nombre. Úsalo sólo cuando el nombre venga de datos. */
export function Icon({ name, fallback = null, ...props }) {
  const Component = iconRegistry[name]
  if (!Component) return fallback
  return createElement(Component, props)
}

Icon.displayName = 'Icon'
