// Archivo generado por scripts/build.mjs. No editar a mano.
const ___ArrowLeft_js = require('./ArrowLeft.js')
exports.ArrowLeft = ___ArrowLeft_js.ArrowLeft
exports.ArrowLeftLong = ___ArrowLeft_js.ArrowLeftLong
const ___ArrowRight_js = require('./ArrowRight.js')
exports.ArrowRight = ___ArrowRight_js.ArrowRight
exports.ArrowRightLong = ___ArrowRight_js.ArrowRightLong
const ___Bag_js = require('./Bag.js')
exports.Bag = ___Bag_js.Bag
exports.ShoppingBag = ___Bag_js.ShoppingBag
const ___BagTimer_js = require('./BagTimer.js')
exports.BagTimer = ___BagTimer_js.BagTimer
exports.OrderPending = ___BagTimer_js.OrderPending
const ___Call_js = require('./Call.js')
exports.Call = ___Call_js.Call
exports.Phone = ___Call_js.Phone
const ___Car_js = require('./Car.js')
exports.Car = ___Car_js.Car
exports.Delivery = ___Car_js.Delivery
const ___Card_js = require('./Card.js')
exports.Card = ___Card_js.Card
exports.CreditCard = ___Card_js.CreditCard
const ___ChevronDown_js = require('./ChevronDown.js')
exports.ChevronDown = ___ChevronDown_js.ChevronDown
const ___ChevronLeft_js = require('./ChevronLeft.js')
exports.ChevronLeft = ___ChevronLeft_js.ChevronLeft
const ___ChevronRight_js = require('./ChevronRight.js')
exports.ChevronRight = ___ChevronRight_js.ChevronRight
const ___CloseCircle_js = require('./CloseCircle.js')
exports.CloseCircle = ___CloseCircle_js.CloseCircle
exports.XCircle = ___CloseCircle_js.XCircle
const ___Danger_js = require('./Danger.js')
exports.Danger = ___Danger_js.Danger
exports.AlertTriangle = ___Danger_js.AlertTriangle
const ___DocumentLike_js = require('./DocumentLike.js')
exports.DocumentLike = ___DocumentLike_js.DocumentLike
exports.Terms = ___DocumentLike_js.Terms
const ___Eye_js = require('./Eye.js')
exports.Eye = ___Eye_js.Eye
const ___EyeSlash_js = require('./EyeSlash.js')
exports.EyeSlash = ___EyeSlash_js.EyeSlash
exports.EyeOff = ___EyeSlash_js.EyeOff
const ___Helmet_js = require('./Helmet.js')
exports.Helmet = ___Helmet_js.Helmet
const ___Home_js = require('./Home.js')
exports.Home = ___Home_js.Home
const ___InfoCircle_js = require('./InfoCircle.js')
exports.InfoCircle = ___InfoCircle_js.InfoCircle
exports.Info = ___InfoCircle_js.Info
const ___Paperclip_js = require('./Paperclip.js')
exports.Paperclip = ___Paperclip_js.Paperclip
exports.Attachment = ___Paperclip_js.Attachment
const ___PersonalCard_js = require('./PersonalCard.js')
exports.PersonalCard = ___PersonalCard_js.PersonalCard
exports.IdCard = ___PersonalCard_js.IdCard
const ___Receipt_js = require('./Receipt.js')
exports.Receipt = ___Receipt_js.Receipt
exports.Order = ___Receipt_js.Order
const ___Search_js = require('./Search.js')
exports.Search = ___Search_js.Search
const ___ShieldTick_js = require('./ShieldTick.js')
exports.ShieldTick = ___ShieldTick_js.ShieldTick
exports.ShieldCheck = ___ShieldTick_js.ShieldCheck
const ___Shop_js = require('./Shop.js')
exports.Shop = ___Shop_js.Shop
const ___Star_js = require('./Star.js')
exports.Star = ___Star_js.Star
const ___TickCircle_js = require('./TickCircle.js')
exports.TickCircle = ___TickCircle_js.TickCircle
exports.CheckCircle = ___TickCircle_js.CheckCircle
const ___User_js = require('./User.js')
exports.User = ___User_js.User
const ___UserSquare_js = require('./UserSquare.js')
exports.UserSquare = ___UserSquare_js.UserSquare
exports.Profile = ___UserSquare_js.Profile
const ____core_createIcon_web_js = require('../core/createIcon.web.js')
exports.createIcon = ____core_createIcon_web_js.createIcon
const ____core_defaults_js = require('../core/defaults.js')
exports.DEFAULTS = ____core_defaults_js.DEFAULTS