// Archivo generado por scripts/build.mjs. No editar a mano.
export { Account } from './Account.js'
export { Add } from './Add.js'
export { AlertCircle } from './AlertCircle.js'
export { ArrowLeft, ArrowLeftLong } from './ArrowLeft.js'
export { ArrowRight, ArrowRightLong } from './ArrowRight.js'
export { Bag, ShoppingBag } from './Bag.js'
export { BagTimer, OrderPending } from './BagTimer.js'
export { Call, Phone } from './Call.js'
export { Car, Delivery } from './Car.js'
export { Card, CreditCard } from './Card.js'
export { ChevronDown } from './ChevronDown.js'
export { ChevronLeft } from './ChevronLeft.js'
export { ChevronRight } from './ChevronRight.js'
export { Clock } from './Clock.js'
export { CloseCircle, XCircle } from './CloseCircle.js'
export { Copy } from './Copy.js'
export { Danger, AlertTriangle } from './Danger.js'
export { DocumentLike, Terms } from './DocumentLike.js'
export { Error } from './Error.js'
export { Eye } from './Eye.js'
export { EyeLine } from './EyeLine.js'
export { EyeSlash, EyeOff } from './EyeSlash.js'
export { GalleryAdd } from './GalleryAdd.js'
export { Helmet } from './Helmet.js'
export { Home } from './Home.js'
export { InfoCircle, Info } from './InfoCircle.js'
export { Location } from './Location.js'
export { Mobile } from './Mobile.js'
export { Moneys } from './Moneys.js'
export { Motorbiker } from './Motorbiker.js'
export { Paperclip, Attachment } from './Paperclip.js'
export { PersonalCard, IdCard } from './PersonalCard.js'
export { Receipt, Order } from './Receipt.js'
export { ScanBarcode } from './ScanBarcode.js'
export { Search } from './Search.js'
export { ShielVerified, ShieldCheck } from './ShielVerified.js'
export { Shop } from './Shop.js'
export { ShoppingBagPlain } from './ShoppingBagPlain.js'
export { Star } from './Star.js'
export { Store } from './Store.js'
export { Succes } from './Succes.js'
export { TickCircle, CheckCircle } from './TickCircle.js'
export { Ticket } from './Ticket.js'
export { User } from './User.js'
export { UserCard } from './UserCard.js'
export { UserSquare, Profile } from './UserSquare.js'
export { Warning } from './Warning.js'
export { createIcon } from '../core/types'
export type { IconComponent, IconProps, IconShape, IconVariant } from '../core/types'
export declare const DEFAULTS: { size: number; color: string; variant: import('../core/types').IconVariant }
