// Archivo generado por scripts/build.mjs. No editar a mano.
export { ArrowLeft, ArrowLeftLong } from './ArrowLeft.js'
export { ArrowRight, ArrowRightLong } from './ArrowRight.js'
export { Bag, ShoppingBag } from './Bag.js'
export { BagTimer, OrderPending } from './BagTimer.js'
export { Call, Phone } from './Call.js'
export { Car, Delivery } from './Car.js'
export { Card, CreditCard } from './Card.js'
export { ChevronDown } from './ChevronDown.js'
export { ChevronLeft } from './ChevronLeft.js'
export { ChevronRight } from './ChevronRight.js'
export { CloseCircle, XCircle } from './CloseCircle.js'
export { Danger, AlertTriangle } from './Danger.js'
export { DocumentLike, Terms } from './DocumentLike.js'
export { Eye } from './Eye.js'
export { EyeSlash, EyeOff } from './EyeSlash.js'
export { Helmet } from './Helmet.js'
export { Home } from './Home.js'
export { InfoCircle, Info } from './InfoCircle.js'
export { Paperclip, Attachment } from './Paperclip.js'
export { PersonalCard, IdCard } from './PersonalCard.js'
export { Receipt, Order } from './Receipt.js'
export { Search } from './Search.js'
export { ShieldTick, ShieldCheck } from './ShieldTick.js'
export { Shop } from './Shop.js'
export { Star } from './Star.js'
export { TickCircle, CheckCircle } from './TickCircle.js'
export { User } from './User.js'
export { UserSquare, Profile } from './UserSquare.js'
export { createIcon } from '../core/types'
export type { IconComponent, IconProps, IconShape, IconVariant } from '../core/types'
export declare const DEFAULTS: { size: number; color: string; variant: import('../core/types').IconVariant }
